PART2_PROCESS_TREE:
  children:
  - children:
    - level: 2
      name: level2.1
      print: false
      token: ''
    - level: 2
      name: level2.2
      print: false
      token: ''
    level: 1
    name: level1.1
    print: true
    token: 1897e7
  - children:
    - level: 2
      name: level2.3
      print: true
      token: ''
    level: 1
    name: level1.2
    print: false
    token: 4b3b63
  - children:
    - level: 2
      name: level2.4
      print: true
      token: ''
    level: 1
    name: level1.3
    print: true
    token: f0eab4
  - children:
    - level: 2
      name: level2.5
      print: true
      token: ''
    level: 1
    name: level1.4
    print: false
    token: 28eacf
  level: 0
  name: level0
  print: true
  token: 1897e74b3b63f0eab428eacf
